/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'macuco' at '24/08/16 12:18 PM' with Gradle 2.13
 *
 * @author macuco, @date 24/08/16 12:18 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
